### ISSUE TITLE
Rename `master` branch of sops repository to `main`?

### ISSUE THREAD

**Issue by felixfontein** [getsops/community#16]
I don't know whether you have any plans for this, but I would guess now - while everything is still being re-set up - is one of the best times to rename the branch.

**Comment by hiddeco** [comment]
This was on my to-do list, but hadn't created an issue for it yet. Will happen as soon as I have handled the primary things around CNCF onboarding.

**Comment by hiddeco** [comment]
https://github.com/getsops/sotp has been switched over to `main`.

**Comment by hiddeco** [comment]
All good!
